language: node_js
node_js:
  - "4"

install:
    - npm install

cache:
  directories:
  - node_modules

script: npm run build

env:
  global:
    - NODE_ENV=production
    - secure: "Xjd/sdw0tv5UYBHjs/7CBRW87H9IywNijO0elnZxIJQb6R1XSfiFdfk3+U+0M5z5VR1pcHI9ZiubJNZMgRtEhM/sw8jFwsHXZQaBz1qjbKPWlybOVMLNdD+iB+CucMwtQ3jlfzOzRcl+hYy1eilZ9tpM2iSmfFYkoRlW/ZL1tRAadB/9wgcVk+SrsfnAZOmBGNIF1ZwjyTHR3zgo6s8lu0ohjKMRbrgrndJArwKfOMeBMFlldL2JBk5p29aYp9JjAGeRQeEqInj3+7jB4Kud68Xdd0rqT1q4+mq4udCYNeNsSxCYk5lGciIhv/Ot1KQvgpNpUngcSTK7Fo6NM1d8IIYccTGtG9BwJ9VPMSh7ybKLS32kA01DhGpNUpbIpoceZYoCxLJ78hgXgUSD9hoTcivkBKBUh9H/5gZlbPychOSCLlWclANyaC8aUCQ80URGjayATGnqyYgwtfpGV4sgMsT0UluK8OvtnTZaubBcPMnJ5xUiRm5QvSu8skCltfykQRlPyoClpsP2D+abMZqEj+hjUkkblfo0ft2h+f4v8QaCHBrH5w8ah75ThBt3BLaHdpGHm+x50YUScGBrjLbL1+/taWgKyJ8Uz1bjkQnvuVf0/7aW7isumaQSpA+w6v7Im9Km0hPOjDJaj405g5Occ8LYf+Lw0vlu0yP1LGW1V8Q="
    - secure: "pj3mtj+EiR4NgvGfm3eWdVmJaUwBzQmWduOJYqxMKrT+5uf/3hNDr3JkhN0Xn50Vk4InVa2b0gStTbZMVoq/HaUi1jfW8Smlbxq2y55aLnE9tGldY8hVSsmEGu0ns96aSPgEeSRG4kiQ9M9OwZRYHJpNRwSo5yqs99/s5UymEQn+EgSWuyo9AmEU27VNyZ8bRG1qf4uLzWPj/CpqdZ44abqdH7sq8JsHDkm+F8qCwTsruLxxNlbxsHBBurUCyVcVvsZwdylNfDhZ10BMor23+MFCykG60HTTuADe4skKHnW9Pp9X+iXgwd05BS4IA5fCuvjg0beyCBmepqKLz6ehRFfc0/oYr9Dx+Oxqu4dzHzTjVVuREKS6SiMquSND4ajgg3M/yrMgfaI/f/TMwSIv9AeJAlIcb+TrDCHF5EYaWpShKxRkO8zI67Iyuiimg9VQ4t+7HjFw9njDaJLBLKiTlBociM/kdnRa1D1eYsXHvMARwUqD8sFiZSA3XsKpUWcaEvY8WR1gjx7bcGUgLJCkaQNJbijwNZ93vdY8RB8+QCo2S15vhYBB/+oXStTdhgy931houvejmpSz3G6PZQ1R/koUo+TjLnsok2IFC2LVA824dbRcmvclT04guIrdg6U+RXBKMDKhYnbOfcjM+K2Vd/AxT/MWzeSsGcp90hxfshI="
    - secure: "iVHnDIMviW/IV+CSb01gDVtRggtTlO5IVh2xWOkZgpkwdM9GIF+TNXtm5nlpRvPNBiSlUVR7xrAEeTKyOgDyIOYElcXjHWKUiMP7Jy3h981hI7SeA8sIcDDrUfs0SlaT7NUcUssZB47onPw05668rf+JkQBHfmUSbCLAu/aUs0OpBGoaFcLpWgHoiBaCZsyWKdXT3NOdwPcUPyj6c5mwz2cuvHNIqpRsFJyv6gXZMU9RQGIMcjYcFvdojOazz7EGTejltwCxph0HlQ5dUUyI11mse6wbeH0d3c03/BEMMsJb7lWpz/+qqQIpabyysQ6qxusmg89DXkwD1vdJOomQ7muNd5N13PYKsxNBJ9QDaU3NZeqJ4d2iowitaC6xpf93diUhOQng81iztOmxoYvaQnBOAe8euMETcY+4R7mau2114bIYWjb6pxumntPoIYKvChvQbij6O1UaCX84Oh6YRosYC6Iy/tMbqcwQ0QBna81i/JwjZc8qRAlcWmhuq1WHn28dwWRITz5tjBW0KCsO27DkatR7Olw8ldCxIW2s67CF9KWCH9CgFggz4Yal6II0YLSivB4UD+b9hL1D1ZGDgwgYpWJj0uyzsDTFi+ViNPtBgrhrywjGVag1EGqEb7uLC3i/m8Z1JUIZmkHg7Mhl0/IgsCJHPJ5dD030WBg3xww="

after_success:
  - ./deploy.sh
